# wrangler.toml (wrangler v3.78.6^)
name = "sub-scraping"
main = "./.output/server/index.mjs"
tsconfig = "./tsconfig.json"
route = { pattern = "sub.wyzie.ru/*", custom_domain = true }

minify = true

[observability]
enabled = true
head_sampling_rate = 1

[build]
command = "pnpm build:cloudflare"
watch_dir = "./.output/server"
